### ISSUE TITLE
This doesn't use a cache for dependencies to be bundled

### ISSUE THREAD

**Issue by lucsoft** [anatoo/vite-deno-plugin#3]
As a user i would like to use URL Imports to import remote typescript files into my vite project and bundle them using vite.
Currently when i have an url import vite ignores it.

My Basic setup:
```
# index.html
<script type="module" src="main.ts"></script>
# main.ts
import { isLeap } from "https://deno.land/std@0.218.2/datetime/is_leap.ts";
document.body.innerHTML += isLeap(new Date());
# vite.config.mts
import { defineConfig, PluginOption } from "npm:vite@5.1.4";
import viteDeno from "https://deno.land/x/vite_deno_plugin@v0.9.4/mod.ts";

export default defineConfig({
    plugins: [
        viteDeno() as PluginOption,
    ],
});
```

i would expect that the deno std would get cached and get bundled into the project, and being able to load the page and seeing a true.

Currently, there is an error thrown because the site tries to load the typescript import.

Extra:
In this project there is a urlImportPlugin but i think it doesn't do anything and i couldn't get it running as vite never tried to resolve these url imports?

**Comment by lucsoft** [comment]
Ahh after some more research i found this only works if you run vite build/preview but not vite dev

**Comment by anatoo** [comment]
In vite's development mode, it is expected behavior that the ESM is not bundled.

**Comment by lucsoft** [comment]
Okay but this kinda breaks that plugin in dev mode? Is the a way its possible to enable esm bundling or at least have custom resolving in dev mode?

@anatoo

**Comment by anatoo** [comment]
@lucsoft 
Currently, TypeScript modules hosted in `deno.land` cannot be loaded with this plugin.
This is because it is not possible on the Vite plugin side to hook the loading of a module specified by a remote URL.
Therefore, the Deno modules you want to load should be local. npm libraries should be loaded via esm.sh.

**Comment by lucsoft** [comment]
Do you know if Turbo would allow to have hooks for this? Kinda a show stopper to invest in Vite 💀
