### ISSUE TITLE
Don't know if it is the plugin or esm.sh fault 😓

### ISSUE THREAD

**Issue by carere** [anatoo/vite-deno-plugin#4]
@anatoo 

Hello, I created a repo from your example react repository, but this time with SolidJS, Solid-router, & Tailwindcss.
I have several problem during build. And I don't know why, could you just clone it and try it out, in order to see if you found something weird or something I did wrong ??

Here is the repository: https://github.com/carere/solid-router-deno-vitejs-tailwind

Thx for your work, it seems like a new step to have a full monorepo with Deno (just need the ViteJS stuff to work properly with Deno 😓)

**Comment by anatoo** [comment]
Apparently, when I load SolidJS via [esm.sh](https://esm.sh), the esbuild target changes to `denonext`. It seems to be broken because of that.
If I add `?target=esnext` and build it, it works.

```
{
  "tasks": {
    "dev": "deno run -A npm:vite . --config ./vite.config.mts",
    "build": "deno run -A npm:vite build . --config ./vite.config.mts",
    "preview": "deno run -A npm:vite preview . --config ./vite.config.mts",
    "optimize": "deno run -A npm:vite optimize . --config ./vite.config.mts"
  },
  "imports": {
    "solid-js": "https://esm.sh/solid-js@1.8.16?target=esnext",
    "solid-js/": "https://esm.sh/solid-js@1.8.16/",
    "solid-js/web": "https://esm.sh/solid-js@1.8.16/web?target=esnext",
    "@solidjs/router": "https://esm.sh/@solidjs/router@0.13.1?target=esnext",
    "@solidjs/router/": "https://esm.sh/@solidjs/router@0.13.1/",
    "tailwindcss": "https://esm.sh/tailwindcss",
    "postcss": "https://esm.sh/postcss",
    "autoprefixer": "https://esm.sh/autoprefixer"
  },
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "solid-js",
    "lib": ["dom", "deno.ns"],
    "types": ["vite/client"]
  }
}
```

```
$ deno task build
Task build deno run -A npm:vite build . --config ./vite.config.mts
vite v5.2.6 building for production...
✓ 15 modules transformed.
dist/index.html                  0.28 kB │ gzip:  0.20 kB
dist/assets/index-ClfK_AET.css   4.77 kB │ gzip:  1.42 kB
dist/assets/index-DEUg1wvL.js   27.53 kB │ gzip: 10.00 kB
✓ built in 2.61s
```

**Comment by carere** [comment]
@anatoo 
Thx for your answer, it worked indeed, now I just have a proble with Solid-router. If you look closely in the main_router.tsx file, the `Route` component is not properly typed.
Also, the router does not fully work (it can go to a specific route through the browser search bar, and update correctly the browser history), but i don't see any changes in the UI when I click on a link.
Anyway, it may be a Solid-router problem, or maybe the way esm.sh build the module.
I think this issue is solved, thx for your help :)
